OPENAI_API_KEY = "your_openai_api_key_here"
SENDGRID_API_KEY = "your_verified_sendgrid_api_key_here"
FROM_EMAIL = "your_verified_sendgrid_email@example.com"
MAIL_FROM_NAME = "recruiter_email_name"
RECRUITER_EMAIL = "youremail@example.com"